version: '3.5'
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./mongodb-data:/data/db
        healthcheck:
            test: "bash -c \"if mongo --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'; then exit 0; fi; exit 1;\""
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s

    foosball_backend:
        image: foospal-backend:development
        container_name: foospal-backend
        restart: always
        ports:
            - "3000:3000/tcp"
        healthcheck:
            test: curl localhost:3000
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s

    foosball_frontend:
        image: foospal-frontend:development
        container_name: foospal-frontend
        ports:
            - "8080:8080/tcp"
        restart: always
        healthcheck:
            test: curl localhost:8080
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
